sys2do/views/auth.py
# -*- coding: utf-8 -*-
'''
###########################################
#  Created on 2011-12-5
#  @author: cl.lam
#  Description:
###########################################
'''
import traceback
from datetime import datetime as dt
from flask import session
from flask.helpers import url_for, flash
from werkzeug.utils import redirect
from flask.blueprints import Blueprint
from flaskext.babel import gettext as _
from sqlalchemy.sql.expression import and_


from sys2do.util.decorator import templated
from sys2do.util.common import _g, getMasterAll, _error
from sys2do.model import DBSession, User
from sys2do.constant import MESSAGE_ERROR, MSG_USER_NOT_EXIST, \
    MSG_WRONG_PASSWORD, MESSAGE_INFO, MSG_SAVE_SUCC
from sys2do.model.master import Customer, CustomerProfile
from sys2do.util.tests import in_group


__all__ = ['bpAuth']



index_url = lambda : url_for('bpRoot.view', action = "index")



bpAuth = Blueprint('bpAuth', __name__)

@bpAuth.route('/login')
@templated("login.html")
def login():
    if session.get('login', None):
        return redirect(index_url())
    return {}



@bpAuth.route('/check', methods = ['GET', 'POST'])
def check():
    try:
        u = DBSession.query(User).filter(and_(User.active == 0, User.name == _g('name'))).one()
    except:
        _error(traceback.print_exc())
        flash(MSG_USER_NOT_EXIST, MESSAGE_ERROR)
        return redirect(url_for('bpAuth.login', next = _g('next')))
    else:
        if not _g('password'):
            flash(MSG_WRONG_PASSWORD, MESSAGE_ERROR)
            return redirect(url_for('bpAuth.login', next = _g('next')))

        if not u.validate_password(_g('password')):
            flash(MSG_WRONG_PASSWORD, MESSAGE_ERROR)
            return redirect(url_for('bpAuth.login', next = _g('next')))
        else:
            #fill the info into the session
            session['login'] = True
            session['user_profile'] = u.populate()
            permissions = set()
            for g in u.groups:
                for p in g.permissions:
                    permissions.add(p.name)
            session['user_profile']['groups'] = [g.name for g in u.groups]
            session['user_profile']['permissions'] = list(permissions)

            if in_group('CUSTOMER'):
                for g in u.groups:
                    if g.type != 0 :
                        for p in g.customer_profile:
                            if p and p.customer_id:
                                session['customer_profile'] = p.customer.populate()
                                break

            if in_group('SUPPLIER'):
                for g in u.groups:
                    if g.type != 0 :
                        for p in g.supplier_profile:
                            if p and p.supplier_id:
                                session['supplier_profile'] = p.supplier.populate()
                                break

            u.last_login = dt.now()

            session.permanent = True

            DBSession.commit()
            if _g('next') : return redirect(_g('next'))
            return redirect(index_url())


@bpAuth.route('/logout')
def logout():
    session.pop('login', None)
    session.pop('user_profile', None)
    if 'customer_profile' in session : session.pop('customer_profile', None)
    if 'supplier_profile' in session : session.pop('supplier_profile', None)
    return redirect(url_for('bpAuth.login'))


@bpAuth.route('/register')
@templated("register.html")
def register():
    return {'customers' : getMasterAll(Customer), }



@bpAuth.route('/save_register', methods = ['GET', 'POST'])
def save_register():
    cid = _g('customer_id' , None)
    user_params = {
                "name" : _g('name'),
                "password" : _g('password'),
                "email" : _g('email'),
                "first_name" : _g('first_name'),
                "last_name" : _g('last_name'),
                "phone" : _g('phone'),
                "mobile" : _g('mobile'),
                   }


    if cid and cid != 'OTHER':
        c = DBSession.query(Customer).get(cid)
        user_params['customer_profile_id'] = c.profile.id
    else:
        cname = _g('name').strip()
        cp = CustomerProfile(name = "PROFILE_%s" % cname.strip().upper().replace(' ', '_'))
        DBSession.add(cp)
        DBSession.flush()
        c = Customer(
                     name = cname,
                     address = _g('address'),
                     profile = cp
                     )
        user_params['customer_profile_id'] = cp.id
        DBSession.add(c)

    DBSession.add(User(**user_params))

    DBSession.commit()
    flash(MSG_SAVE_SUCC, MESSAGE_INFO)
    return redirect(url_for('bpAuth.login'))

sys2do/views/master.py
# -*- coding: utf-8 -*-
'''
###########################################
#  Created on 2011-12-12
#  @author: cl.lam
#  Description:
###########################################
'''
from flask.blueprints import Blueprint
from flask.views import View
from flask.helpers import url_for, flash
from sys2do.constant import MESSAGE_ERROR, MSG_NO_SUCH_ACTION
from werkzeug.utils import redirect
from sys2do.util.common import _g
from sys2do.views import BasicView
from sys2do.model.master import Customer
from sys2do.model import DBSession
from flask.templating import render_template

__all__ = ['bpMaster']

bpMaster = Blueprint('bpMaster', __name__)

class MasterView(BasicView):

    def index(self):
        type = _g('type')
        master_mapping = {
                          'customer' : Customer,
#                          'vendor' : Vendor,
#                          'item' : Item,
                          }

        if type not in master_mapping :
            flash(MSG_NO_SUCH_ACTION, MESSAGE_ERROR)
            return redirect('/index')

        clz = master_mapping[type]
        result = DBSession.query(clz).filter(clz.active == 0).order_by(clz.name)
        return render_template('master/%s_index.html' % type, result = result)


    def update(self):
        return ''


bpMaster.add_url_rule('/', view_func = MasterView.as_view('view'), defaults = {'action':'index'})
bpMaster.add_url_rule('/<action>', view_func = MasterView.as_view('view'))

sys2do/templates/change_pw.html
{% extends "master.html" %}

{% block extJS %}
<script language="JavaScript" type="text/javascript">
//<![CDATA[
	function tosave(){
		var msg = Array();
		if(!$("#old_pw").val()){
			msg.push('请填写原始密码');
		}
		if(!$('#new_pw').val()){
			msg.push('请填写新密码');
		}
		if(!$('#new_repw').val()){
			msg.push('请填写确认密码');
		}
		if($('#new_pw').val()!=$('#new_repw').val()){
			msg.push('新密码与确认密码不相符！');
		}
		
		if(msg.length > 0){
			alert(msg.join('\n'));
		}else if(confirm('确定要修改密码吗？')){
			$("form").submit();
		}
	
	}
//]]>
</script>
{% endblock %}
	
{% block content %}
	<h1>修改用户密码</h1>
	<form action="/save_pw" method="posh">
	<table>
		<tr>
			<td>旧密码</td>
			<td><input type="password" name="old_pw" id="old_pw" value="" class="must_input"/></td>
		</tr>
		<tr>
			<td>新密码</td>
			<td><input type="password" name="new_pw" id="new_pw" value="" class="must_input"/></td>
		</tr>
		<tr>
			<td>确认密码</td>
			<td><input type="password" name="new_repw" id="new_repw" value="" class="must_input"/></td>
		</tr>
	</table>
	<p><input type="button" value="提交" onclick="tosave()"/></p>
	</form>
{% endblock %}

sys2do/templates/dashboard.html
{% extends "master.html" %}
{% block subtitle %} - 管理员控制台{% endblock %}

{% block extJS %}

<script language="JavaScript" type="text/javascript">
//<![CDATA[
	function append(id,l){
		var e = $(id);
		
		var html = '';
		
		for(var i=0;i<l.list.length;i++){
		   var tmp = l.list[i];
		   html += '<li class="level_two item_line"><a href="/order/review?id='+tmp.id+'">'+tmp.ref_no+'</a></li>';
		}
		$(id+'_count').text(l.count);
		e.after(html);
	}

	$(document).ready(function(){
		$.getJSON('/order/ajax_todo_list',
				  {'t' : nowstr()},
				  function(r){
				      if(r.result != 0){ return; }
				      
				      $('.item_line').remove();
				      append('#orders_new',r.data.orders_new);
				      append('#order_receiver',r.data.order_receiver);
				      append('#order_inhouse',r.data.order_inhouse);
				      append('#order_sorted',r.data.order_sorted);
				  }
		);
	})
//]]>
</script>
{% endblock %}

{% block content %}
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
  <tbody><tr>
    <td width="220" class="main_left_td" valign="top">
    <div class="todo_list_header">
    <img width="220" height="31" src="/static/images/system/main_page_03.jpg"></div>
      <div class="todo_list_div">
        <div>
        	<ul>
           	  <li class="level_one" id="orders_new">需要指派收件人(<span id="orders_new_count">0</span>)</li>               
            </ul>
        </div>
        <div>
			<ul>
            	<li class="level_one" id="order_receiver">等待入仓(<span id="order_receiver_count">0</span>)</li>
            </ul>
        </div>
        <div>
			<ul>
            	<li class="level_one" id="order_inhouse">等待分拣(<span id="order_inhouse_count">0</span>)</li>
            </ul>
        </div>
        <div>
			<ul>
            	<li class="level_one" id="order_sorted">等待出仓(<span id="order_sorted_count">0</span>)</li>
            </ul>
        </div>
    </div></td>
     
     
     
     <td valign="top" class="main_right_td">

	  {% if 'MANAGE_USER' is get_permission%}
      <div class="nav_tab" onclick="redirect('{{url_for('bpAdmin.view',action='user')}}')">
        <div class="header_div"></div>
        <div class="body_div"><img width="80" height="80" src="/static/images/system/img_um.jpg"><span>用户管理</span>
          <p>关于用户管理的一些说明。说明用户管理功能的用法与注意事项。</p>
        </div>
      </div>
      {% endif %}
      
      {% if 'MANAGE_GROUP' is get_permission%}
      <div class="nav_tab" onclick="redirect('{{url_for('bpAdmin.view',action='group')}}')">
        <div class="header_div"></div>
        <div class="body_div"><img width="80" height="80" src="/static/images/system/img_gm.jpg"><span>组管理</span>
          <p>关于组管理的一些说明。说明组管理功能的用法与注意事项。</p>
        </div>
      </div>
      {% endif %}
      
      {% if 'MANAGE_PERMISSION' is get_permission%}
      <div class="nav_tab" onclick="redirect('{{url_for('bpAdmin.view',action='permission')}}')">
        <div class="header_div"></div>
        <div class="body_div"><img width="80" height="80" src="/static/images/system/img_permissions.jpg"><span>权限管理</span>
          <p>关于权限管理的一些说明。说明权限管理功能的用法与注意事项。</p>
        </div>
      </div>
      {% endif %}
      
      </td>

     
     
     
  </tr>
</tbody></table>

{% endblock %}

sys2do/templates/index.html
{% extends "master.html" %}
{% block subtitle %} - 首页{% endblock %}

{% block extJS %}

<script language="JavaScript" type="text/javascript">
//<![CDATA[
	function append(id,l){
		var e = $(id);
		
		var html = '';
		
		for(var i=0;i<l.list.length;i++){
		   var tmp = l.list[i];
		   html += '<li class="level_two item_line"><a href="/order/review?id='+tmp.id+'">'+tmp.ref_no+'</a></li>';
		}
		$(id+'_count').text(l.count);
		e.after(html);
	}

	function refreshToDoList(){
		$.getJSON('/order/ajax_todo_list',
				  {'t' : nowstr()},
				  function(r){
				      if(r.result != 0){ return; }
				      
				      $('.item_line').remove();
				      append('#order_draft',r.data.order_draft);
				      append('#orders_new',r.data.orders_new);
				      append('#order_receiver',r.data.order_receiver);
				      append('#order_inhouse',r.data.order_inhouse);
				      append('#order_sorted',r.data.order_sorted);
				  }
		);
	}

	setInterval(refreshToDoList,1000*60*5); //5min


	$(document).ready(function(){
		refreshToDoList();
	})
//]]>
</script>
{% endblock %}

{% block content %}
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
  <tbody><tr>
    <td width="220" class="main_left_td" valign="top">
    <div class="todo_list_header">
    <img width="220" height="31" src="/static/images/system/main_page_03.jpg"></div>
      <div class="todo_list_div">
        <div>
        	<ul>
           	  <li class="level_one" id="order_draft">条码新增订单(<span id="order_draft_count">0</span>)</li>               
            </ul>
        </div>
        <div>
        	<ul>
           	  <li class="level_one" id="orders_new">需要指派收件人(<span id="orders_new_count">0</span>)</li>               
            </ul>
        </div>
        <div>
			<ul>
            	<li class="level_one" id="order_receiver">等待入仓(<span id="order_receiver_count">0</span>)</li>
            </ul>
        </div>
        <div>
			<ul>
            	<li class="level_one" id="order_inhouse">等待分拣(<span id="order_inhouse_count">0</span>)</li>
            </ul>
        </div>
        <div>
			<ul>
            	<li class="level_one" id="order_sorted">等待出仓(<span id="order_sorted_count">0</span>)</li>
            </ul>
        </div>
    </div></td>
     <td height="550" class="main_right_td main_right_td_bg" valign="top">欢迎登录到深福合力物流管理系统。</td>
  </tr>
</tbody></table>
	
{% endblock %}

sys2do/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>{{_("Logistics Management")}} - 登录</title>
<link rel="icon" type="image/ico" href="{{url_for('static', filename='favicon.ico')}}"></link> 
<link href="{{url_for('static', filename='css/common_style.css')}}" rel="stylesheet" type="text/css" />
<link href="{{url_for('static', filename='css/system_style.css')}}" rel="stylesheet" type="text/css" />
	
<script src="{{url_for('static', filename='js/jquery-1.7.1.min.js')}}" type="text/javascript"></script>	

<style type="text/css">
body {
	background-image: url(/static/images/system/index_04.jpg);
	background-repeat: repeat-x;
	background-color:#39565e;
}
.input_login{
	background:url(/static/images/system/input_login.png) no-repeat scroll transparent;
    border:none;
    font-family: "微软雅黑";
    font-size: 18px;
    height: 35px;
    /*text-indent: 15px;*/
    width: 216px;
	padding:0px 0px 0px 10px
}
</style>

<script language="JavaScript" type="text/javascript">
//<![CDATA[
	$(document).ready(function(){
		$("#name").focus();
	});
//]]>
</script>


</head>

<body>
<form action="{{url_for('bpAuth.check')}}" method="post">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td><img src="/static/images/system/index_01.jpg" width="474" height="85" /></td>
  </tr>
  <tr>
    <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="407" align="left" valign="top"><img src="/static/images/system/index_05.jpg" width="407" height="308" /></td>
        <td align="left" valign="top"><table width="523" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td height="124" class="point_login_td">
            	<h2>{% for category,message in get_flashed_messages(with_categories=true) %}
            		{{message}}&nbsp;
            	{% endfor %}
            	</h2>
            </td>
          </tr>
          <tr>
            <td height="319" background="/static/images/system/index_08.jpg"><table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="230">&nbsp;</td>
                <td height="30">用户名：</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                <td><input type="text" name="name" class="input_login" id="name"/></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                <td height="30">密&nbsp;&nbsp;码：</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                <td><input type="password" name="password" class="input_login" id="password"/></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td width="70"><img src="/static/images/system/index_08_03.jpg" width="49" height="51" /></td>
                    <td><input type="image" src="/static/images/system/index_08_06.jpg" width="77" height="21" /></td>
                  </tr>
                </table></td>
              </tr>
            </table></td>
          </tr>
        </table></td>
      </tr>
    </table></td>
  </tr>
</table>
</form>
</body>
</html>

sys2do/templates/macros.html
{% macro show_direction(values,f) -%}
    {%if values.get('field',None) == f: %}
		{%if values.get('direction',None) == 'desc' %}
			<a href="#" onclick="toSort('{{f}}','asc')"><img src="/static/images/system/down.png"/></a>
		{%else %}
			<a href="#" onclick="toSort('{{f}}','desc')"><img src="/static/images/system/up.png"/></a>
		{%endif%}
	{% else %}
		<a href="#" onclick="toSort('{{f}}','desc')"><img src="/static/images/system/updown.gif"/></a>
	{% endif %}
{%- endmacro %}



{% macro show_approve(value) -%}
	{% if value == 0 %}
		未审核
	{% elif value == 1 %}
		通过
	{% elif value == 2 %}
		不通过
	{% endif %}
{%- endmacro %}


{% macro show_paid(value) -%}
	{% if value == 0 %}
		未付
	{% elif value == 1 %}
		已付
	{% endif %}
{%- endmacro %}


{% macro show_supplier_paid(value) -%}
	{% if value == 0 %}
		未付
	{% elif value == 1 %}
		已付
	{% endif %}
{%- endmacro %}


{% macro show_exception(value) -%}
	{% if value %}
		是
	{% endif %}
{%- endmacro %}



{% macro show_less_qty(value) -%}
	{% if value %}
		是
	{% endif %}
{%- endmacro %}




{% macro show_return(value) -%}
	{% if value == 0 %}
		未返
	{% else %}
		已返
	{% endif %}
{%- endmacro %}


{% macro show_exception(value) -%}
	{% if value == 0 %}
		否
	{% else %}
		是
	{% endif %}
{%- endmacro %}



{% macro show_lessqty(value) -%}
	{% if value == 0 %}
		否
	{% else %}
		是
	{% endif %}
{%- endmacro %}


{% macro show_discount(value) -%}
	{% if value == 0 %}
		未返
	{% else %}
		已返
	{% endif %}
{%- endmacro %}


{% macro mypaginate(records) -%}
	{{records.pager(format='$link_first $link_previous ~3~ $link_next $link_last, 共计 $item_count 条记录',
					show_if_single_page=True,
					symbol_first='第一页',
					symbol_last='最后一页',
					symbol_previous='上一页',
					symbol_next='下一页')}}
{%- endmacro %}


{% macro select(id,list,value,class='',style='',blank_option=true) -%}
	<select name="{{id}}" id="{{id}}" class="{{class}}" style="{{style}}">
		{% if blank_option %}
          <option value=""></option>
        {% endif %}
          {% for o in list%}
              {% if o.id == value%}
                  <option value="{{o.id}}" selected="selected">{{o}}</option>
              {% else %}
                  <option value="{{o.id}}">{{o}}</option>
              {% endif %}
          {% endfor %}
      </select>
{%- endmacro %}



{% macro location_option(location_list,value,space=0) -%}
	{% for l in location_list %}
		{% if l.id == value %}
			<option value="{{l.id}}" selected="selected" full_ids="{{l.full_path_ids}}">{{('&nbsp;' * space)|safe}}{{l.name}}</option>
		{% else %}
			<option value="{{l.id}}" full_ids="{{l.full_path_ids}}">{{('&nbsp;' * space)|safe}}{{l.name}}</option>
		{% endif %}
		{{location_option(l.children,value,space+3)}}
	{% endfor %}
{%- endmacro %}



{% macro location_select(id,list,value,class='',style='',blank_option=true) -%}
	<select name="{{id}}" id="{{id}}" class="{{class}}" style="{{style}}">
		{% if blank_option %}
          <option value=""></option>
        {% endif %}
        {{location_option(list,value,0)}}
	</select>
{%- endmacro %}



sys2do/templates/main.html
{% extends "master.html" %}
{% block subtitle %} - 控制台{% endblock %}

{% block extJS %}

<script language="JavaScript" type="text/javascript">
//<![CDATA[
	function append(id,l){
		var e = $(id);
		
		var html = '';
		
		for(var i=0;i<l.list.length;i++){
		   var tmp = l.list[i];
		   html += '<li class="level_two item_line"><a href="/order/review?id='+tmp.id+'">'+tmp.ref_no+'</a></li>';
		}
		$(id+'_count').text(l.count);
		e.after(html);
	}
	
	
	function refreshToDoList(){
		$.getJSON('/order/ajax_todo_list',
				  {'t' : nowstr()},
				  function(r){
				      if(r.result != 0){ return; }
				      
				      $('.item_line').remove();
				      append('#order_draft',r.data.order_draft);
				      append('#orders_new',r.data.orders_new);
				      append('#order_receiver',r.data.order_receiver);
				      append('#order_inhouse',r.data.order_inhouse);
				      append('#order_sorted',r.data.order_sorted);
				  }
		);
	}

	setInterval(refreshToDoList,1000*60*5); //5min
	

	$(document).ready(function(){
		refreshToDoList();
	})
//]]>
</script>
{% endblock %}

{% block content %}
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
  <tbody><tr>
    <td width="220" class="main_left_td" valign="top">
    <div class="todo_list_header">
    <img width="220" height="31" src="/static/images/system/main_page_03.jpg"></div>
      <div class="todo_list_div">
        <div>
        	<ul>
           	  <li class="level_one" id="order_draft">条码新增订单(<span id="order_draft_count">0</span>)</li>
            </ul>
        </div>
        <div>
        	<ul>
           	  <li class="level_one" id="orders_new">需要指派收件人(<span id="orders_new_count">0</span>)</li>               
            </ul>
        </div>
        <div>
			<ul>
            	<li class="level_one" id="order_receiver">等待入仓(<span id="order_receiver_count">0</span>)</li>
            </ul>
        </div>
        <div>
			<ul>
            	<li class="level_one" id="order_inhouse">等待分拣(<span id="order_inhouse_count">0</span>)</li>
            </ul>
        </div>
        <div>
			<ul>
            	<li class="level_one" id="order_sorted">等待出仓(<span id="order_sorted_count">0</span>)</li>
            </ul>
        </div>
    </div></td>

     <td valign="top" class="main_right_td">
     
      {% if 'MANAGE_ORDER' is get_permission%}
      <div class="nav_tab" onclick="redirect('{{url_for('bpOrder.view')}}')">
      	<div class="header_div"></div>
      	<div class="body_div"><img width="80" height="80" src="/static/images/system/img_so.jpg"><span>订单管理</span>
      		<p>关于订单管理的一些说明。说明订单管理功能的用法与注意事项。</p>
      	</div>
      </div>
      {% endif %}
      
      {% if 'MANAGE_DELIVER' is get_permission%}
      <div class="nav_tab" onclick="redirect('{{url_for('bpDeliver.view')}}')">
        <div class="header_div"></div>
        <div class="body_div"><img width="80" height="80" src="/static/images/system/img_po.jpg"><span>配送管理</span>
          <p>关于送货单管理的一些说明。说明送货单管理功能的用法与注意事项。</p>
        </div>
      </div>
      {% endif %}
      
      
      {% if 'MANAGE_FIN' is get_permission%}
      <div class="nav_tab" onclick="redirect('{{url_for('bpFin.view')}}')">
        <div class="header_div"></div>
        <div class="body_div"><img width="80" height="80" src="/static/images/system/img_cm.jpg"><span>财务管理</span>
          <p>关于财务管理的一些说明。说明财务管理功能的用法与注意事项。</p>
        </div>
      </div>
   	  {% endif %}
   	  
      <div class="nav_tab" onclick="redirect('{{url_for('bpInventory.view')}}')">
        <div class="header_div"></div>
        <div class="body_div"><img width="80" height="80" src="/static/images/system/img_cm.jpg"><span>仓储管理</span>
          <p>关于仓储管理的一些说明。说明仓储管理功能的用法与注意事项。</p>
        </div>
      </div>
   	  {% if 'MANAGE_FIN' is get_permission%}
   	  {% endif %}
     
  </tr>
</tbody></table>

{% endblock %}

sys2do/templates/register.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
 <head>
  <title>{{_('Register')}}</title>
  <meta name="Author" content="">
  <meta name="Keywords" content="">
  <meta name="Description" content="">
  <link rel="stylesheet" type="text/css" href="" />
  <style type="text/css">

  </style>

  <script type="text/javascript" src=""></script>
  <script language="JavaScript" type="text/javascript">
    //<![CDATA[
          
    //]]>
   </script>
 </head>

 <body>
 		<div>
 			{% for category,message in get_flashed_messages(with_categories=true) %}
				<p>{{message}}</p>
			{% endfor %}
 		</div>
		<form action="{{url_for('bpAuth.save_register')}}" method="post">
			<table>
				<tr>
					<td>{{_('Customer')}}</td>
					<td>
						<select name="customer_id" id="customer_id" onchange="changecustomer(this)">
							{% for c in customers%}
								<option value="{{c.id}}">{{c.name}}</option>
							{% endfor %}
							<option value="OTHER">---- {{_('Other')}} ----</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>{{_('Customer Name')}}</td>
					<td><input type="text" name="customer_name" id="customer_name" value=""/></td>
				</tr>
				<tr>
					<td>{{_('Address')}}</td>
					<td><input type="text" name="source_address" id="source_address" value=""/></td>
				</tr>
			</table>
			<br />
			<table>
				<tr>
					<td>{{_('User Name')}}</td>
					<td><input type="text" name="name" id="name" value=""/></td>
				</tr>
				<tr>
					<td>{{_('E-mail')}}</td>
					<td><input type="text" name="email" id="email" value=""/></td>
				</tr>
				<tr>
					<td>{{_('Password')}}</td><td><input type="password" name="password" value=""/></td>
				</tr>
				<tr>
					<td>{{_('Confirmed Password')}}</td>
					<td><input type="password" name="repassword" value=""/></td>
				</tr>
				<tr>
					<td>{{_('First Name')}}</td>
					<td><input type="text" name="first_name" id="first_name" value=""/></td>
				</tr>
				<tr>
					<td>{{_('Last Name')}}</td>
					<td><input type="text" name="last_name" id="last_name" value=""/></td>
				</tr>
				<tr>
					<td>{{_('Phone')}}</td>
					<td><input type="text" name="phone" id="phone" value=""/></td>
				</tr>
				<tr>
					<td>{{_('Mobile')}}</td>
					<td><input type="text" name="mobile" id="mobile" value=""/></td>
				</tr>
				<tr><td colspan="2"><input type="submit" value="{{_('Save')}}" class="btn"/></td></tr>
			</table>	
		</form>
 </body>
</html>

sys2do/templates/search_orders.html
{% extends "master.html" %}

{% block extJS %}

{% endblock %}

{% block content %}
	{% for (no,log) in logs %}
		<h3>{{no}}</h3>

		
		<table border="1" cellpadding="3" cellspacing="3">
			<tr>
				<td>{{_('Time')}}</td>
				<td>{{_('Content')}}</td>
			</tr>
			{% for l in log %}
				<tr>
					<td>{{l.create_time|ft}}</td>
					<td>{{l.remark}}</td>
				</tr>
			{% endfor %}
		</table>
	
	{% endfor %}
{% endblock %}

sys2do/templates/track.html
{% extends "master.html" %}

{% block extJS %}

{% endblock %}

{% block content %}
		<table border="1" cellpadding="3" cellspacing="3">
			<tr>
				<td>{{_('Ordr No')}}</td>
				<td>{{_('Order Time')}}</td>
				<td>{{_('Status')}}</td>
			</tr>
		{% for order in orders %}
				<tr>
					<td>{{order.no}}</td>
					<td>{{order.create_time|ft}}</td>
					<td>{{order.status|showStatus}}</td>
				</tr>
		{% endfor %}
		</table>
	
{% endblock %}